name: release

on:
  workflow_dispatch:
    inputs:
      micro:
        type: number
        description: "The last revision number of the release. Useful if there are multiple releases on the same day"
        default: 0
        required: false
  schedule:
    - cron: "20 4 * * 3"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: "refs/heads/main"

      - name: set output
        id: vars
        run: echo "tag=$(date '+%Y.%-m.%-d').${{ inputs.micro || '0' }}" >> $GITHUB_OUTPUT

      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: 22.x

      - name: install packages
        run: yarn install

      - name: update reviews
        run: yarn run update-reviews

      - name: commit reviews & tag
        uses: EndBug/add-and-commit@v9
        id: sync
        with:
          add: "src/reviews.json"
          message: "sync reviews"
          tag: ${{ steps.vars.outputs.tag }}
        continue-on-error: true

      - name: compile
        if: ${{ github.event_name == 'workflow_dispatch' || steps.sync.outputs.committed }}
        run: yarn build
        env:
          BUILD_VERSION: ${{ steps.vars.outputs.tag }}

      - name: archive source
        uses: thedoctor0/zip-release@main
        if: ${{ github.event_name == 'workflow_dispatch' || steps.sync.outputs.committed }}
        with:
          type: "zip"
          filename: "source.zip"
          exclusions: "*.git* /*node_modules/* /*dist/*"

      - name: archive chrome release
        uses: thedoctor0/zip-release@main
        if: ${{ github.event_name == 'workflow_dispatch' || steps.sync.outputs.committed }}
        with:
          type: "zip"
          filename: "chrome.zip"
          directory: "dist/chrome"

      - name: archive firefox release
        uses: thedoctor0/zip-release@main
        if: ${{ github.event_name == 'workflow_dispatch' || steps.sync.outputs.committed }}
        with:
          type: "zip"
          filename: "firefox.zip"
          directory: "dist/firefox"

      - name: create release
        uses: ncipollo/release-action@v1
        if: ${{ github.event_name == 'workflow_dispatch' || steps.sync.outputs.committed }}
        with:
          artifacts: "dist/chrome/chrome.zip,dist/firefox/firefox.zip"
          generateReleaseNotes: true
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}
          tag: ${{ steps.vars.outputs.tag }}

      - name: publish firefox add-on
        uses: browser-actions/release-firefox-addon@latest
        if: ${{ github.event_name == 'workflow_dispatch' || steps.sync.outputs.committed }}
        with:
          addon-id: ziyi-zip
          addon-path: dist/firefox/firefox.zip
          source-path: source.zip
          auth-api-issuer: ${{ secrets.MOZILLA_AUTH_API_ISSUER }}
          auth-api-secret: ${{ secrets.MOZILLA_AUTH_API_SECRET }}
          approval-note: |
            To build this add-on, Node.js and Yarn are required.
            Run the following commands:
            1. yarn install
            2. yarn build:firefox
            The add-on code will be found in dist/firefox

      - name: publish chrome extension
        uses: browser-actions/release-chrome-extension@latest
        if: ${{ github.event_name == 'workflow_dispatch' || steps.sync.outputs.committed }}
        with:
          extension-id: kgjlmncdpdpcmidkkalcdppigdocdnmf
          extension-path: dist/chrome/chrome.zip
          oauth-client-id: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          oauth-client-secret: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
          oauth-refresh-token: ${{ secrets.GOOGLE_OAUTH_REFRESH_TOKEN }}
